---
kind: pipeline
type: docker
name: learn-app-development

environment:
  namespace: default

clone:
  depth: 50

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
      - rm -f .tags
      - printf "%s\n" $(git describe --abbrev=0 --tags || echo $DRONE_BRANCH | tr '/' '-') > .tags
      - printf "Tags to build\n-------------\n%s\n" $(cat .tags)

  - name: Go image (build)
    image: plugins/kaniko
    settings:
      skip_tls_verify: false # set to true for testing registries ONLY with self-signed certs
      build_args:
        - COMMIT_SHA=${DRONE_COMMIT_SHA}
        - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: dxas90/bobr-status
      dockerfile: Dockerfile
      registry: harbor.dxas90.xyz

image_pull_secrets:
  - dockerconfig

trigger:
  branch:
    - develop
    - feature/*
  event:
    - push
# services:
#   - name: docker
#     image: docker:dind
#     privileged: true
#     volumes:
#       - name: dockersock
#         path: /var/run

# volumes:
#   - name: dockersock
#     temp: {}
