apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - ./deployment-patch.yaml

resources:
  - ../../base/

images:
  - name: dxas90/bobr-status
    newTag: prod

commonLabels:
  owner: gitops
  app: bobr-status
generatorOptions:
  labels:
    type: generated
    team: DevOps
  annotations:
    note: generated
