apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./base

commonLabels:
  app: bobr-status
  owner: gitops
generatorOptions:
  annotations:
    note: generated
  labels:
    team: DevOps
    type: generated
