apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - ./deployment-patch.yaml

resources:
  - ../../base/

images:
  - name: dxas90/bobr-status
    newTag: develop

commonLabels:
  app: bobr-status
  owner: gitops
generatorOptions:
  annotations:
    note: generated
  labels:
    team: DevOps
    type: generated
